$filePath = "C:\SourceDocs\AutoGeneratedDoc.docx"

[ref]$SaveFormat = "microsoft.office.interop.word.WdSaveFormat" -as [type]
$word=new-object -ComObject "Word.Application"
$doc=$word.documents.Add()
$word.Visible=$True

$selection=$word.Selection

$selection.Font.Name="Segoe UI Light"
$selection.Font.Size=36
$selection.TypeText(("Sample Document"))

$selection.Font.Name="Times New Roman"
$selection.Font.Size=12

$paragraph = "`n`nLorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim."
$paragraph += "`nFusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede."
$paragraph += "`nMauris et orci. Aenean nec lorem. In porttitor. Donec laoreet nonummy augue."


$selection.TypeText(($paragraph))

$doc.saveas([ref] $filePath, [ref]$saveFormat::wdFormatDocument)